In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./Datasets/2-emails.csv')
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [3]:
df.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [5]:
df = df.drop(['Email No.'], axis = 1)
df.head()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,1,0,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,1,0,0

In [7]:
from sklearn.model_selection import train_test_split
x = df.drop('Prediction', axis = 1)
y = df['Prediction']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Confusion metric", confusion_matrix(y_test, y_pred))
print("classification report", classification_report(y_test, y_pred))

Accuracy Score 0.8628019323671497
Confusion metric [[646  93]
 [ 49 247]]
classification report               precision    recall  f1-score   support

           0       0.93      0.87      0.90       739
           1       0.73      0.83      0.78       296

    accuracy                           0.86      1035
   macro avg       0.83      0.85      0.84      1035
weighted avg       0.87      0.86      0.87      1035

In [10]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print("Accuracy Score", accuracy_score(y_test, y_pred))
print("Confusion metric", confusion_matrix(y_test, y_pred))
print("classification report", classification_report(y_test, y_pred))

Accuracy Score 0.8173913043478261
Confusion metric [[727  12]
 [177 119]]
classification report               precision    recall  f1-score   support

           0       0.80      0.98      0.88       739
           1       0.91      0.40      0.56       296

    accuracy                           0.82      1035
   macro avg       0.86      0.69      0.72      1035
weighted avg       0.83      0.82      0.79      1035